# Generated by Django 5.2.16 on 2026-08-01 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('abn', models.CharField(blank=True, max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=150)),
                ('trade_type', models.CharField(blank=True, help_text='e.g. builder, electrician, plumber, concreter', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'partners',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_role', models.CharField(blank=True, help_text='e.g. concreting, framing, electrical', max_length=50)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('partner', models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.PROTECT, related_name='project_partners', to='partners.partner')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='project_partners', to='construction.project')),
            ],
            options={
                'db_table': 'project_partners',
                'constraints': [models.UniqueConstraint(fields=('project', 'partner', 'trade_role'), name='unique_project_partner_trade_role')],
            },
        ),
    ]
