# Generated by Django 5.2.16 on 2026-08-01 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='construction.project')),
                ('sales_rep', models.ForeignKey(db_column='sales_rep_id', on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='accounts.staff')),
            ],
            options={
                'db_table': 'commissions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('source', models.CharField(blank=True, choices=[('google_ads', 'Google Ads'), ('referral', 'Referral'), ('walk_in', 'Walk-in'), ('website', 'Website'), ('other', 'Other')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_sales', models.ForeignKey(blank=True, db_column='assigned_sales_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='accounts.staff')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('site_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, db_column='lead_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='crm.lead')),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
