# Generated by Django 5.2.16 on 2026-08-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('google_ads', 'Google Ads'), ('referral', 'Referral'), ('walk_in', 'Walk-in'), ('website', 'Website'), ('online_store', 'Online Store'), ('cold_call', 'Cold Call'), ('public_relations', 'Public Relations'), ('sales_email_alias', 'Sales Email Alias'), ('seminar_partner', 'Seminar Partner'), ('internal_seminar', 'Internal Seminar'), ('trade_show', 'Trade Show'), ('web_download', 'Web Download'), ('web_research', 'Web Research'), ('chat', 'Chat'), ('x_twitter', 'X (Twitter)'), ('facebook', 'Facebook'), ('other', 'Other')], max_length=30, null=True, verbose_name='Lead Source'),
        ),
    ]
