# Generated by Django 5.2.16 on 2026-08-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_expand_lead_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
