# Generated by Django 5.2.16 on 2026-08-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_add_lead_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
