# Generated by Django 5.2.16 on 2026-08-01 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('construction', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.client'),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_rep',
            field=models.ForeignKey(blank=True, db_column='sales_rep_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='projectstageprogress',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='stage_progress', to='construction.project'),
        ),
        migrations.AddField(
            model_name='projectstageprogress',
            name='stage',
            field=models.ForeignKey(db_column='stage_id', on_delete=django.db.models.deletion.PROTECT, related_name='progress_rows', to='construction.projectstage'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='posted_by',
            field=models.ForeignKey(blank=True, db_column='posted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_updates', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='construction.project'),
        ),
        migrations.AddConstraint(
            model_name='projectstageprogress',
            constraint=models.UniqueConstraint(fields=('project', 'stage'), name='unique_project_stage'),
        ),
    ]
